"""Generate the MkDocs Examples page from the repository's examples tree.

The hook deliberately creates both the Markdown page and its downloadable
source copies at build time.  Consequently, a documentation build always
reflects the examples that were checked out for that build.
"""

from __future__ import annotations

import os
import re
import shutil
import stat
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
EXAMPLES_DIR = PROJECT_ROOT / "examples"
DOCS_DIR = PROJECT_ROOT / "docs"
PAGE_PATH = DOCS_DIR / "examples.md"
DOWNLOADS_DIR = DOCS_DIR / "downloads" / "examples"

LANGUAGES = {
    ".ini": "ini",
    ".json": "json",
    ".md": "markdown",
    ".py": "python",
    ".sh": "bash",
    ".toml": "toml",
    ".txt": "text",
    ".urdf": "xml",
    ".xml": "xml",
    ".yaml": "yaml",
    ".yml": "yaml",
}


def _is_text_file(path: Path) -> bool:
    """Return whether a file can be displayed safely as source code."""
    with path.open("rb") as file:
        sample = file.read(8192)
    if b"\0" in sample:
        return False
    try:
        sample.decode("utf-8")
    except UnicodeDecodeError:
        return False
    return True


def _fence_for(source: str) -> str:
    """Choose a Markdown fence longer than any backtick run in *source*."""
    longest_run = max((len(run) for run in re.findall(r"`+", source)), default=0)
    return "`" * max(3, longest_run + 1)


def _remove_readonly(operation, path, _exception_info) -> None:
    """Allow generated copies of read-only example assets to be refreshed."""
    os.chmod(path, stat.S_IWRITE)
    operation(path)


def _render_file(source_path: Path) -> str:
    relative_path = source_path.relative_to(EXAMPLES_DIR)
    destination = DOWNLOADS_DIR / relative_path
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source_path, destination)

    source = source_path.read_text(encoding="utf-8")
    language = LANGUAGES.get(source_path.suffix.lower(), "text")
    fence = _fence_for(source)
    download_path = relative_path.as_posix()

    final_newline = "" if source.endswith("\n") else "\n"
    return f'''## `{relative_path.as_posix()}`\n\n[Download file](downloads/examples/{download_path}){{ .md-button .md-button--primary download="{source_path.name}" }}\n\n{fence}{language}\n{source}{final_newline}{fence}\n'''


def on_config(config, **kwargs):
    """Create the Examples page before MkDocs discovers documentation files."""
    if not EXAMPLES_DIR.is_dir():
        raise RuntimeError(f"Examples directory not found: {EXAMPLES_DIR}")

    # This directory is entirely generated by this hook, so removing it also
    # prevents deleted example files from lingering in published documentation.
    if DOWNLOADS_DIR.exists():
        shutil.rmtree(DOWNLOADS_DIR, onerror=_remove_readonly)

    sections = [
        "# Examples\n",
        "Each example below is generated directly from the repository's "
        "`examples/` directory during the documentation build. Use the copy "
        "button on a code block or download the original file.\n",
    ]

    files = sorted(
        path
        for path in EXAMPLES_DIR.rglob("*")
        if path.is_file() and "__pycache__" not in path.parts
    )
    text_files = [path for path in files if _is_text_file(path)]
    skipped_files = [path for path in files if path not in text_files]

    for source_path in text_files:
        sections.append(_render_file(source_path))

    if skipped_files:
        skipped = ", ".join(f"`{path.relative_to(EXAMPLES_DIR).as_posix()}`" for path in skipped_files)
        sections.append(f"\n!!! warning \"Binary files\"\n\n    These files are available in the repository but are not displayed as code: {skipped}.\n")

    PAGE_PATH.write_text("\n".join(sections), encoding="utf-8")
    return config
